export interface User {
    id:number
    id_str:string
    name:string
    screen_name:string
    location:string
    profile_location:string
    description:string
    url:string
    entities:any
    protected:boolean
    followers_count:number
    friends_count:number
    listed_count:number
    created_at:string
    favourites_count:number
    utc_offset:string
    time_zone:string
    geo_enabled:boolean
    verified:boolean
    statuses_count:number
    lang:string
    status:any
    contributors_enabled:boolean
    is_translator:boolean
    is_translation_enabled:boolean
    profile_background_color:string
    profile_background_image_url:string
    profile_background_image_url_https:string
    profile_background_tile:boolean
    profile_image_url:string
    profile_image_url_https:string
    profile_banner_url:string
    profile_link_color:string
    profile_sidebar_border_color:string
    profile_sidebar_fill_color:string
    profile_text_color:string
    profile_use_background_image:boolean
    has_extended_profile:boolean
    default_profile:boolean
    default_profile_image:boolean
    following:string
    follow_request_sent:string
    notifications:string
    translator_type:string
    withheld_in_countries:any
}

export interface Tweets {
    created_at:string
    id:number
    id_str:string
    text:string
    truncated:boolean
    entities:any
    source:string
    in_reply_to_status_id:string
    in_reply_to_status_id_str:string
    in_reply_to_user_id:string
    in_reply_to_user_id_str:string
    in_reply_to_screen_name:string
    user:any
    geo:string
    coordinates:string
    place:string
    contributors:string
    is_quote_status:boolean
    quoted_status_id:number
    quoted_status_id_str:string
    quoted_status:any
    retweet_count:number
    favorite_count:number
    favorited:boolean
    retweeted:boolean
    possibly_sensitive:boolean
    lang:string
}

export interface FollowersList {
    id:number
    id_str:string
    name:string
    screen_name:string
    location:string
    description:string
    url:string
    entities:any
    protected:boolean
    followers_count:number
    friends_count:number
    listed_count:number
    created_at:string
    favourites_count:number
    utc_offset:string
    time_zone:string
    geo_enabled:boolean
    verified:boolean
    statuses_count:number
    lang:string
    status:any
    contributors_enabled:boolean
    is_translator:boolean
    is_translation_enabled:boolean
    profile_background_color:string
    profile_background_image_url:string
    profile_background_image_url_https:string
    profile_background_tile:boolean
    profile_image_url:string
    profile_image_url_https:string
    profile_link_color:string
    profile_sidebar_border_color:string
    profile_sidebar_fill_color:string
    profile_text_color:string
    profile_use_background_image:boolean
    has_extended_profile:boolean
    default_profile:boolean
    default_profile_image:boolean
    following:string
    follow_request_sent:string
    notifications:string
    muting:string
    blocking:string
    blocked_by:string
    translator_type:string
    withheld_in_countries:any
}

export interface FollowingsList {
    id:number
    id_str:string
    name:string
    screen_name:string
    location:string
    description:string
    url:string
    entities:any
    protected:boolean
    followers_count:number
    friends_count:number
    listed_count:number
    created_at:string
    favourites_count:number
    utc_offset:string
    time_zone:string
    geo_enabled:boolean
    verified:boolean
    statuses_count:number
    lang:string
    status:any
    contributors_enabled:boolean
    is_translator:boolean
    is_translation_enabled:boolean
    profile_background_color:string
    profile_background_image_url:string
    profile_background_image_url_https:string
    profile_background_tile:boolean
    profile_image_url:string
    profile_image_url_https:string
    profile_link_color:string
    profile_sidebar_border_color:string
    profile_sidebar_fill_color:string
    profile_text_color:string
    profile_use_background_image:boolean
    has_extended_profile:boolean
    default_profile:boolean
    default_profile_image:boolean
    following:string
    follow_request_sent:string
    notifications:string
    muting:string
    blocking:string
    blocked_by:string
    translator_type:string
    withheld_in_countries:any
}

export interface Search {
    created_at:string
    id:number
    id_str:string
    text:string
    truncated:boolean
    metadata:any
    source:string
    in_reply_to_status_id:string
    in_reply_to_status_id_str:string
    in_reply_to_user_id:string
    in_reply_to_user_id_str:string
    in_reply_to_screen_name:string
    user:any
    geo:string
    coordinates:string
    place:string
    contributors:string
    is_quote_status:boolean
    retweet_count:number
    favorite_count:number
    favorited:boolean
    retweeted:boolean
    lang:string
}

